### ISSUE TITLE
Make sure all developers have a working dev environment

### ISSUE THREAD

**Issue by ahedgpath** [mustachematt/JamNotJelly-Note-Taker#17]
I cloned the repo to my local machine and couldn't get it work. I didn't have a ton of time to troubleshoot though.
I'm wondering if the virtual environment (venv) might be more hassle than it's worth. That's the only part of the Mega Flask Tutorial we didn't setup in our web programming class.
Here is Dr D's notes re: setup and virtual environments:
"Forget about the virtual environment
- Not useful in dedicated environments
- Containers are dedicated environments
- Each PA instance is a container of sorts"
Helpful link for setting up environment: [Setting Up Environment](https://docs.google.com/presentation/d/1xdUgjFmCKzG1k_ua06HttZSy1nBYXIzwANHQxxnBrJY/edit#slide=id.p3)

**Comment by mmari13** [comment]
Yes, the virtual environment is not needed

**Comment by mustachematt** [comment]
Yeah, When I put the pages on the pythonanywhere site, I tried the virtual environment at first and gave up on it because it added more complexity than what it was worth. Therefore, I skipped that part when I finally got the pages up, so there's no virtual environment on it.

**Comment by ahedgpath** [comment]
I can run it locally now...was a simple fix.

**Comment by lujacky380** [comment]
How did you get it working? Can you post the basic instructions?

**Comment by ahedgpath** [comment]
The problem with my env was that I had been trying to use the virtual environment and my start.bat file was in the root of the repo. It appears the mysite subfolder is the only directory we care about though since that's what is running on PA. So I moved my start.bat to the root of the mysite subfolder and just simply ignored the venv stuff. That cleared the errors for me. I'm not sure if it's helpful, but here are some instructions specific to my local environment: 
[Local Dev Env](https://drive.google.com/drive/folders/1bjh61e6U0DOz7KLHvBPWXru3QFr004eX)
