### ISSUE TITLE
Create a logo and add it to the website

### ISSUE THREAD

**Issue by ahedgpath** [mustachematt/JamNotJelly-Note-Taker#18]
Let's subdivide this:

- [x] Sketch out a logo concept
- [x] Draw it in image editing software, something like Photoshop or GIMP
- [x] Add this image to the repository in the "static" folder
- [x] Decide which page(s) this image should go on
- [x] Add it to those pages by making references to them in the html files
- [x] Determine where on the page it should go
- [x] Commit changes made to this point
- [x] Add it to the pythonanywhere site (which could be expressed as a separate list)

**Comment by mustachematt** [comment]
Let's subdivide this:

- [ ] Sketch out a logo concept
- [ ] Draw it in image editing software, something like Photoshop or GIMP
- [ ] Add this image to the repository in the "templates" folder
- [ ] Decide which page(s) this image should go on
- [ ] Add it to those pages by making references to them in the html files
- [ ] Determine where on the page it should go
- [ ] Commit changes made to this point
- [ ] Add it to the pythonanywhere site (which could be expressed as a separate list)
