### ISSUE TITLE
Create and finish a burn down chart for Sprint 1

### ISSUE THREAD

**Issue by mustachematt** [mustachematt/JamNotJelly-Note-Taker#2]
This is something that could be done in either Excel or Google Sheets. It might be better to do it with Google Sheets because it would make it easier and quicker for everyone to access as you can put a link to it on the wiki. However, I know that Excel provides more features for making graphs. Either way, this needs done by Friday.

IMPORTANT: If you make it in Excel, make sure not to submit this as an .xl file. Do it as a .pdf or something like that.

Remember to add the following:

- The days of the week as the x axis

- The number of cards put in the sprint backlog (project to do list) in total as the highest possible value on the y axis

- An "ideal" line to compare with the line representing how much was actually accomplished

You can reference this (this is part of the required class reading anyways): https://en.wikipedia.org/wiki/Burn_down_chart

**Comment by ahedgpath** [comment]
Something like this?...
[https://drive.google.com/open?id=1L7RqyvVi9ZTl5JOFUPKBUHPHY6LvN3uFD6kVVNpeq2U]

**Comment by lujacky380** [comment]
Amy, that looks exactly like what I thought we'd need. I think that's good in terms of the information we need to present in a burn down chart. We just need to keep this updated as we finish tasks.
