### ISSUE TITLE
Create test suite for database operations from the website

### ISSUE THREAD

**Issue by mustachematt** [mustachematt/JamNotJelly-Note-Taker#43]
For now, the suite should test the following functionality:

On the Sign Up page, check to see if:
- [ ] It will validate the email account entered.
- [x] If the email is not valid, it throws the appropriate error message.
- [ ] The username that was entered is not already taken.
- [ ] If the username is taken, it throws the appropriate error message.
- [ ] The passwords entered in "password" and "confirm password" match.
- [ ] If the passwords don't match, it throws the appropriate error message.
- [ ] The user has not entered information that matches an account already in 
       the database.
- [ ] If it does match, it tells the user that the account already exists.
- [ ] If all of the information the user enters is "good," verify that the account is
       made successfully. 
        
On the Login page, check to see if:
- [ ] The username is in the database.
- [x] If the username is in the database, check if the password entered matches.
- [ ] If it does match, allow the user to log in.
- [ ] If the username is not in the database, the user cannot login.
- [ ] If the password does not match the username, the user cannot login.
- [ ] If the password field is empty, the user cannot log in.
- [ ] The remember me checkbox functions as intended.

Besides the above, also: 
- [ ] Check to make sure that all links on the site work correctly.

**Comment by mmari13** [comment]
New criteria for this issue:

- [ ] Set up selenium and chromedriver 
- [ ] Organize/name test files so they ran with unnitest framework 
- [ ] Set up flask and python on testers personal computers
