### ISSUE TITLE
Time is different

### ISSUE THREAD

**Issue by ssarowar** [mustachematt/JamNotJelly-Note-Taker#55]
The time should be the user's local time.

**Comment by mmari13** [comment]
fix the timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
in the models.py file

**Comment by mustachematt** [comment]
https://stackoverflow.com/questions/62151/datetime-now-vs-datetime-utcnow

Just change datetime.utcnow to datetime.now
