### ISSUE TITLE
Test registration errors 

### ISSUE THREAD

**Issue by mmari13** [mustachematt/JamNotJelly-Note-Taker#58]
On the Sign Up page, check to see if:
- [ ] ~~Change the sign up box id to say sign up instead of login box~~
>decided against this because cameron doesn't want two elements that do the same style
>just added a name to the sighnup box to differentiate it from the login box
- [ ] ~~It will validate the email account entered.~~
>we think this is actually done by the db orm or the flask code itself, not us
- [x] If the email is not valid, it throws the appropriate error message.
- [x] The username that was entered is not already taken.
- [x] If the username is taken, it throws the appropriate error message.
>we added to the error message 
- [x] The passwords entered in "password" and "confirm password" match.
- [x] If the passwords don't match, it throws the appropriate error message.
- [x] The user has not entered information that matches an account already in 
       the database.
- [x] If it does match, it tells the user that the account already exists.
>We changed error html text to say this 

- [ ] ~~If all of the information the user enters is "good," verify that the account is
       made successfully.~~
>This test would not be repeatable, maybe ask professor whats the right thing to do

**Comment by smorri55** [comment]
All registration webdriver scripts created successfully.
