### ISSUE TITLE
Display account information on the account page

### ISSUE THREAD

**Issue by mmari13** [mustachematt/JamNotJelly-Note-Taker#61]
- [x] Display username and about me
- [x] Allow user to change username if chosen username is not already taken
- [x] If username is taken, display error and don't save
- [x] Add about me column to user db table
- [x] Allow user to change about me statement. Commit changes to db and display updates.

**Comment by ahedgpath** [comment]
I removed the id="Main_Body" from the div tag in account.html. CSS will need updated for this pg.
