### ISSUE TITLE
Test sign up from the homepage 

### ISSUE THREAD

**Issue by mmari13** [mustachematt/JamNotJelly-Note-Taker#68]
On the Sign Up page, check to see if:

- [x] If the email is not valid, it throws the appropriate error message.
- [x] If the username is taken, it throws the appropriate error message.
- [x] If the passwords don't match, it throws the appropriate error message.
- [x] if the user entered an email that is already in use it throws appropriate error message
- [x] If all of the information the user enters is "good," verify that the account is
       made successfully.

**Comment by smorri55** [comment]
all tests created successfully
