### ISSUE TITLE
Need to decide which Python version we are using for the website

### ISSUE THREAD

**Issue by mustachematt** [mustachematt/JamNotJelly-Note-Taker#7]
I figure the newest version 3.7.4 is probably the way to go, but I want to make sure we are all on the same page. It would cause a lot of wasted time if there was an issue we came across and it was due to us using different versions of Python. For example, there are some syntax differences between 2.7 and 3.7.

**Comment by lujacky380** [comment]
What version did we decide to use? Just the newest 3.7.4?

**Comment by mustachematt** [comment]
Yeah, we decided on 3.7.4, the newest version
