### ISSUE TITLE
Making a new note asks for wrong date format

### ISSUE THREAD

**Issue by mmill224** [mustachematt/JamNotJelly-Note-Taker#84]
![date_issue](https://user-images.githubusercontent.com/55215015/68887264-b0ff7d80-06e6-11ea-96a5-11e4cff0c772.png)
The textbox has default text in it that says "dd/mm/yyyy" but it really wants "mm/dd/yyyy"
Either of these formats is fine as long as it's consistent with the prompt

**Comment by ahedgpath** [comment]
Updated format of due date placeholder to be mm/dd/yyyy
